[package]
name = "loess"
version = "0.2.5"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2024"
rust-version = "1.86"
description = "Small proc macro grammar- and parser-generator providing great UX."
# documentation intentionally defaulted
readme = "../README.md"
# homepage
repository = "https://github.com/Tamschi/loess"
license = "MIT OR Apache-2.0"
keywords = ["proc-macro", "grammar", "parser", "generator", "dsl"]
categories = ["development-tools::procedural-macro-helpers"]

publish = false

[features]
#TODO (breaking): Remove this alongside optional modules.
rust_grammar = []

# Uses Syn to add basic support for more Rust grammar.
opaque_rust_grammar = ["rust_grammar", "dep:syn", "dep:quote"]

[dependencies]
proc-macro2 = { version = "1.0.34", features = ["span-locations"] }
quote = { version = "1.0.40", default-features = false, optional = true }

# Private dependency! Do not implement Loess traits on Syn types or vice versa.
syn = { version = "2.0.100", optional = true, default-features = false, features = [
    "clone-impls",
    "full",
    "parsing",
    "printing",
] }

#TODO (breaking): Remove this alongside optional modules.
[package.metadata.docs.rs]
all-features = true

[package.metadata.cargo-semver-checks.lints]
workspace = true
