[package]
name = "loess"
version = "0.2.2"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2024"
rust-version = "1.86"
description = "Small proc macro grammar and parser (generator) with great UX."
# documentation intentionally defaulted
readme = true
# homepage
repository = "https://github.com/Tamschi/Asteracea"
license = "MIT OR Apache-2.0"
keywords = ["proc-macro", "grammar", "parser", "generator", "dsl"]
categories = ["development-tools::procedural-macro-helpers"]

publish = true

[features]
rust_grammar = []

# Uses Syn to add basic support for more Rust grammar.
opaque_rust_grammar = ["rust_grammar", "dep:syn", "dep:quote"]

[dependencies]
proc-macro2 = "1.0.34"
quote = { version = "1.0.40", default-features = false, optional = true }

# Private dependency! Do not implement Loess traits on Syn types or vice versa.
syn = { version = "2.0.100", optional = true, default-features = false, features = [
    "clone-impls",
    "full",
    "parsing",
    "printing",
] }

[package.metadata.docs.rs]
all-features = true
