use super::{Punctuation, SPunct};

pub type Plus = Punctuation<(SPunct<'+', false>,)>;
pub type Minus = Punctuation<(SPunct<'-', false>,)>;
pub type Star = Punctuation<(SPunct<'*', false>,)>;
pub type Slash = Punctuation<(SPunct<'/', false>,)>;
pub type Percent = Punctuation<(SPunct<'%', false>,)>;
pub type Caret = Punctuation<(SPunct<'^', false>,)>;
pub type Not = Punctuation<(SPunct<'!', false>,)>;
pub type And = Punctuation<(SPunct<'&', false>,)>;
pub type Or = Punctuation<(SPunct<'|', false>,)>;
pub type AndAnd = Punctuation<(SPunct<'&', true>, SPunct<'&', false>)>;
pub type OrOr = Punctuation<(SPunct<'|', true>, SPunct<'|', false>)>;
pub type Shl = Punctuation<(SPunct<'<', true>, SPunct<'<', false>)>;
pub type Shr = Punctuation<(SPunct<'>', true>, SPunct<'>', false>)>;
pub type PlusEq = Punctuation<(SPunct<'+', true>, SPunct<'=', false>)>;
pub type MinusEq = Punctuation<(SPunct<'-', true>, SPunct<'=', false>)>;
pub type StarEq = Punctuation<(SPunct<'*', true>, SPunct<'=', false>)>;
pub type SlashEq = Punctuation<(SPunct<'/', true>, SPunct<'=', false>)>;
pub type PercentEq = Punctuation<(SPunct<'%', true>, SPunct<'=', false>)>;
pub type CaretEq = Punctuation<(SPunct<'^', true>, SPunct<'=', false>)>;
pub type AndEq = Punctuation<(SPunct<'&', true>, SPunct<'=', false>)>;
pub type OrEq = Punctuation<(SPunct<'|', true>, SPunct<'=', false>)>;
pub type ShlEq = Punctuation<(SPunct<'<', true>, SPunct<'<', true>, SPunct<'=', false>)>;
pub type ShrEq = Punctuation<(SPunct<'>', true>, SPunct<'>', true>, SPunct<'=', false>)>;
pub type Eq = Punctuation<(SPunct<'=', false>,)>;
pub type EqEq = Punctuation<(SPunct<'=', true>, SPunct<'=', false>)>;
pub type Ne = Punctuation<(SPunct<'!', true>, SPunct<'=', false>)>;
pub type Gt = Punctuation<(SPunct<'>', false>,)>;
pub type Lt = Punctuation<(SPunct<'<', false>,)>;
pub type Ge = Punctuation<(SPunct<'>', true>, SPunct<'=', false>)>;
pub type Le = Punctuation<(SPunct<'<', true>, SPunct<'=', false>)>;
pub type At = Punctuation<(SPunct<'@', false>,)>;
pub type Underscore = Punctuation<(SPunct<'_', false>,)>;
pub type Dot = Punctuation<(SPunct<'.', false>,)>;
pub type DotDot = Punctuation<(SPunct<'.', true>, SPunct<'.', false>)>;
pub type DotDotDot = Punctuation<(SPunct<'.', true>, SPunct<'.', true>, SPunct<'.', false>)>;
pub type DotDotEq = Punctuation<(SPunct<'.', true>, SPunct<'.', true>, SPunct<'=', false>)>;
pub type Comma = Punctuation<(SPunct<',', false>,)>;
pub type Semi = Punctuation<(SPunct<';', false>,)>;
pub type Colon = Punctuation<(SPunct<':', false>,)>;
pub type ColonColon = Punctuation<(SPunct<':', true>, SPunct<':', false>)>;
pub type PathSep = Punctuation<(SPunct<':', true>, SPunct<':', false>)>;
pub type RArrow = Punctuation<(SPunct<'-', true>, SPunct<'>', false>)>;
pub type FatArrow = Punctuation<(SPunct<'=', true>, SPunct<'>', false>)>;
pub type Pound = Punctuation<(SPunct<'#', false>,)>;
pub type Dollar = Punctuation<(SPunct<'$', false>,)>;
pub type Question = Punctuation<(SPunct<'?', false>,)>;
pub type Tilde = Punctuation<(SPunct<'~', false>,)>;
